### ISSUE TITLE
bad handling when multiple errors are emitted

### ISSUE THREAD

**Issue by mknj** [hashtagchris/node-awaitify-stream#5]
The module works great with one try{} catch block per stream.
Having multiple try {} catch and multiple emitted errors gives strange results.
The following example produces and endless "error 3" loop.
Expected output: (errors may appear at different positions because of async nature of streams)
```
1
error A
2
error B
error C
3
```

actual output:
```
error C
error C
error C
...
```

```
var JSONStream = require('json-stream')
const aw = require('awaitify-stream')
var stream = JSONStream()
let reader = aw.createReader(stream)
buggy()
async function buggy () {
  let chunk = 0
  while (chunk != null) {
    try {
      chunk = await reader.readAsync()
      console.log(chunk)
    } catch (e) {
      console.log('error', e)
    }
  }
}

stream.write('1\n')
stream.emit('error', 'A')
stream.write('2\n')
stream.emit('error', 'B')
stream.emit('error', 'C')
stream.write('3\n')
stream.end()
```

**Comment by mknj** [comment]
simple fix in code:
let errors=[]
...
on("error", ... errors.push(err)

in asyncRead()

let error=errors.shift()

**Comment by hashtagchris** [comment]
Thanks @mknj for reporting the issue and the suggested fix!
